### ISSUE TITLE
NOAA backend subdirectory change breaks get_wind_data.py

### ISSUE THREAD

**Issue by trevor229** [darksidelemm/cusf_predictor_wrapper#6]
A few days ago the NOAA website used to get wind data changed their directory structure such that, for example `/cgi-bin/filter_gfs_0p50.pl?dir=/gfs.########` no longer works. The change seems to only be the addition of a subdirectory for the data to be in called `atmos`. As such, changing the URL to `/cgi-bin/filter_gfs_0p50.pl?dir=/gfs.########/atmos` works. 

I only use the `get_wind_data.py` script for my fork of this repo and I fixed this issue by modifying line 97 and adding `/atmos` to the value of `_filter_params['dir']` as below:

`_filter_params['dir'] = "/gfs.%s/atmos" % (_model_timestring)`

I am unsure of how this would affect the main application as I do not implement it in the project I use.

**Comment by darksidelemm** [comment]
I fixed this 12 days ago: https://github.com/darksidelemm/cusf_predictor_wrapper/commit/1425a7f787eed89ea14d5746a6c8be0eadea49e8

**Comment by trevor229** [comment]
Apologies, should have looked to see if it was fixed first.
