### ISSUE TITLE
Dependencies for flawless install

### ISSUE THREAD

**Issue by MikeTango** [darksidelemm/cusf_predictor_wrapper#7]
Hi,

i made it compile without errors being thrown by adding libgeos-dev, as well as libatlas-base-dev described here:

https://numpy.org/devdocs/user/troubleshooting-importerror.html 

It still keeps nagging about 
"eccodes 1.3.3 has requirement numpy<1.20, but you'll have numpy 1.21.2 which is incompatible." but that doesn't stop it from running.

**Comment by darksidelemm** [comment]
I've added these to the dependencies list in the readme, thanks!
